/**
 * Creating a sidebar enables you to: * create an ordered group of docs * send docs to different sidebar * turn a docs group into a "collapsible sidebar" * learn more at https://docusaurus.io/docs/sidebar#sidebar-categories
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{
    type: 'autogenerated', dirName: '.'
  }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
